name = "test-drive"
version = "0.4.0"
license = "Apache-2.0 OR MIT"
maintainer = ["@awvwgk"]
author = ["Sebastian Ehlert"]
copyright = "2020-2021 Sebastian Ehlert"
description = "The simple testing framework"
keywords = ["testing-framework", "unit-testing"]
