@PACKAGE_INIT@

set("TESTDRIVE_WITH_QP" @TESTDRIVE_WITH_QP@)
set("TESTDRIVE_WITH_XDP" @TESTDRIVE_WITH_XDP@)
set("TESTDRIVE_WITH_IEEE_IS_NAN" @TESTDRIVE_WITH_IEEE_IS_NAN@)

enable_language("Fortran")

if(NOT TARGET "@PROJECT_NAME@::@PROJECT_NAME@")
  include("${CMAKE_CURRENT_LIST_DIR}/@PROJECT_NAME@-targets.cmake")
endif()
